spring.application.name=tech10x.ukm
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ukm}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:qwerty}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=dd-MM-yyyy

app.jwt.secret=${JWT_SECRET:5jXOBwylAGfd3c+OoCbVOV6kf5oT2KwRMNbdtqLoqSw=}
app.jwt.expiration=${JWT_EXPIRATION:86400000}
#########otp##########
app.otp.length=${OTP_LENGTH:6}
app.otp.expiration-minutes=${OTP_EXPIRATION_MINUTES:5}
app.otp.max.attempt.allow=${MAX_OTP_ALLOW_PER_USER}