spring.application.name=tech10x.ukm
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

spring.jackson.time-zone=Asia/Kolkata
spring.jackson.date-format=dd-MM-yyyy

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=${JWT_EXPIRATION}
#########otp##########
app.otp.length=${OTP_LENGTH}
app.otp.expiration-minutes=${OTP_EXPIRATION_MINUTES}
app.otp.max.attempt.allow=${MAX_OTP_ALLOW_PER_USER}